#!/bin/bash

ping -c 50 localhost

OLDPWD=`pwd`

cd testbed

rm testfile*

echo "Single connection"

for i in {1..10}
do
	./client --run single | grep Took | cut -d ' ' -f 2
done

echo "Parallel connections"

for i in {1..10}
do
	./client --run parallel | grep Took | cut -d ' ' -f 2
done

echo "Persistent connection"

for i in {1..10}
do
	./client --run persistent | grep Took | cut -d ' ' -f 2
done

echo "Pipelined requests"

for i in {1..10}
do
	./client --run pipelined | grep Took | cut -d ' ' -f 2
done

rm testfile*

cd $OLDPWD

/usr/bin/osascript << EOF

tell application "Mail"
	
	set theNewMessage to make new outgoing message with properties {subject:"Test suite complete.", content:"Yay!", visible:true}
	tell theNewMessage
		make new to recipient at end of to recipients with properties {address:"r@hul.im"}
		send
	end tell

end tell

EOF

